# -*- coding: utf-8 -*-
"""estrutura_condicional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H8enZXwCLrTvwctXBXrI1dnXiZixkQpi

Estruturas condicionais
"""

idade = 17

if idade < 15:
  print("não pode votar")
  print("você tem menos de 17 anos")
elif idade < 18 or idade >= 70:
  print("voto opciional")
else:
  print("voto obrigatorio")

lista = [10, 5, 0, 1]
for v in lista:
  print(v)
  # o 'v in lista' irá assumir os valores da lista, pode ser usado sempre q vc quiser repetir um valor da lista