# -*- coding: utf-8 -*-
"""introdução.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZHdAkJ1dHSNz40aTFgimyTFujbJB16y
"""

t = (1,2,3)
print(t)
print(type(t))
print(len(t))

print(t[0])
print(t[len(t)-1])
print(t[-2])

t[1] = 100

tabela = ("nome", "Idade", "Altura")
linha = ("Amelia", 20, 1.65)
print (tabela)
print (linha)

l = [3,2,1]
print(l)
print(type(l))

l[1] = 100
print(l)

l.append("pokemon")
l.pop(1)
print(l)
print(len(l))

d = {"nome": "Helena", "idade": 20, "altura": 1.65}
print(d)
print(type(d))

print(d["nome"])
print(d["idade"])
print(d["altura"])

print(d["nome"])
d["trabalha"] = True
print(d)

d2 = {"nome": ["Selmo", "Léo"], "idade": [20, 21], "altura": [1.65, 1.75]}
print(d2)

print(d2["nome"][1])
print(d2["idade"][0])
print(d2["altura"][0])